name: Build and Release BibleLookup

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v0.1.0, v0.2.0, etc.

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir & Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '26.2'
          version-type: strict

      - name: Install dependencies
        run: $env:MIX_ENV = "prod"; mix deps.get

      - name: Build Release
        run: $env:MIX_ENV = "prod"; mix release bible_lookup

      - name: Zip Release
        run: Compress-Archive -Path _build\prod\rel\bible_lookup\* -DestinationPath bible_lookup.zip

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: bible_lookup.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

