name: Build and release BibleLookup

on:
  push:
    tags:
      - 'v*'     # Run on version tags like v0.1.0, v0.2.0, etc.

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.4'
          otp-version: '26.3'

      - name: Install Hex and Rebar
        run: mix local.hex --force && mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Build escript
        run: mix escript.build

      - name: Rename to .exe
        run: Rename-Item -Path bible_lookup -NewName bible_lookup.exe

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload .exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: bible_lookup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

